sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

services:
  - postgresql

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  - export PATH=/opt/ghc/7.8.4/bin:$PATH

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

before_script:
  - psql -c 'create database yesod_test;' -U postgres
  # Set postgres user credentials.
  - export PGUSER="postgres"
  - export PGPASS=""

script:
  - stack --no-terminal --skip-ghc-check test
